all:
  children:
    home_milkyway:
      children:
        rpi5:
          hosts:
            vega:
              ansible_host: 192.168.1.230
              ansible_user: armand
        rpi4:
          hosts:
            rigel:
              ansible_host: 192.168.1.231
              ansible_user: armand
        rpi1:
          hosts:
            saiph:
              ansible_host: 192.168.1.60
              ansible_user: ansible
    andromeda_m31:
      children:
        rpi1:
          hosts:
            g1:
              ansible_host: 10.10.10.11
              ansible_user: ansible
    triangulum_m33:
      children:
        rpi1:
          hosts:
            ngc604:
              ansible_host: 10.10.20.11
              ansible_user: ansible
