all:
  children:
    home_milkyway:
      children:
        rpi4:
          hosts:
            rigel:
              ansible_host: 192.168.1.40
              ansible_user: ansible
        rpi5:
          hosts:
            vega:
              ansible_host: 192.168.1.50
              ansible_user: ansible
        rpi1:
          hosts:
            saiph:
              ansible_host: 192.168.1.60
              ansible_user: ansible
    andromeda_m31:
      children:
        rpi1:
          hosts:
            g1:
              ansible_host: 10.10.10.11
              ansible_user: ansible
    triangulum_m33:
      children:
        rpi1:
          hosts:
            ngc604:
              ansible_host: 10.10.20.11
              ansible_user: ansible
