---
- name: Restart sysstat
  systemd:
    name: sysstat
    state: restarted
  when: ansible_facts['service_mgr'] == 'systemd'

- name: Restart sysstat-collect timer
  systemd:
    name: sysstat-collect.timer
    state: restarted
    enabled: true
  when: ansible_facts['service_mgr'] == 'systemd'

- name: Restart sysstat-summary timer
  systemd:
    name: sysstat-summary.timer
    state: restarted
    enabled: true
  when: ansible_facts['service_mgr'] == 'systemd'
