---
galaxy_info:
  author: intergalactic
  description: Docker monitoring tools (ctop) and aliases for container monitoring
  license: Proprietary - All Rights Reserved, ExNada Inc.
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - monitoring
    - docker
    - containers
    - cli

dependencies: []
